# Generated by Django 3.2.6 on 2021-11-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiolist',
            name='radio_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
