# Generated by Django 3.2.6 on 2021-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_radiolist_radio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiolist',
            name='radio_host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
