# Generated by Django 3.2.6 on 2021-11-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_radiolist_radio_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio', to='stations.radiolist')),
            ],
        ),
        migrations.CreateModel(
            name='RadioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_history_session', to='stations.radiohistory')),
            ],
        ),
    ]
