# Generated by Django 3.2.6 on 2021-11-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_auto_20211122_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiosession',
            name='img_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
