# Generated by Django 3.2.6 on 2021-11-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_radiosession_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiolist',
            name='play_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
