# Generated by Django 3.2.6 on 2021-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_radiolist_play_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='country_flag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='radiolist',
            name='rss_feed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
