# Generated by Django 3.2.6 on 2021-11-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_rssfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='pub_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
