# Generated by Django 3.2.6 on 2021-12-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_rssfeed_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
