# Generated by Django 3.2.6 on 2021-12-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0013_countries_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radioCountryFeed', to='stations.countries'),
        ),
    ]
