# Generated by Django 3.2.6 on 2021-12-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_rssfeed_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiolist',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
