# Generated by Django 3.2.6 on 2021-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_radiolist_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='AD_Zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebarAD', models.TextField(blank=True, help_text='Left SideBar Ad', null=True)),
                ('newsSideAD', models.TextField(blank=True, help_text='News Sidebar Ad', null=True)),
                ('home_ad', models.TextField(blank=True, help_text='add between radio', null=True)),
                ('radio_ad', models.TextField(blank=True, help_text='add between radio', null=True)),
            ],
        ),
    ]
