# Generated by Django 3.2.6 on 2021-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0016_ad_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_zones',
            name='access_name',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
