# Generated by Django 3.2.6 on 2021-12-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0017_ad_zones_access_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_zones',
            name='radioPlayerAD',
            field=models.TextField(blank=True, help_text='News Sidebar Ad, Size: 300x250', null=True),
        ),
        migrations.AlterField(
            model_name='ad_zones',
            name='home_ad',
            field=models.TextField(blank=True, help_text='add between radio, Size=728x90', null=True),
        ),
        migrations.AlterField(
            model_name='ad_zones',
            name='newsSideAD',
            field=models.TextField(blank=True, help_text='News Sidebar Ad, Size: 300x250', null=True),
        ),
        migrations.AlterField(
            model_name='ad_zones',
            name='radio_ad',
            field=models.TextField(blank=True, help_text='add between radio, Size=728x90', null=True),
        ),
        migrations.AlterField(
            model_name='ad_zones',
            name='sidebarAD',
            field=models.TextField(blank=True, help_text='Left SideBar Ad, Size: 300x600', null=True),
        ),
    ]
