# Generated by Django 3.2.6 on 2021-12-18 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0018_auto_20211214_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_radio', to='stations.radiolist')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSession', to='stations.usersession')),
            ],
        ),
    ]
